name: Setup Repository Properties

on:
  push:
    branches: [main]

jobs:
  setup-properties:
    runs-on: ubuntu-latest
    if: github.run_number == 1  # Only run on first push to new repo
    
    steps:
      - name: Generate App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      
      - name: Check if properties already exist
        id: check_properties
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            try {
              const { data } = await github.rest.repos.getAllCustomProperties({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              
              const hasRole = data.some(prop => prop.property_name === 'role');
              core.setOutput('has_properties', hasRole);
              console.log('Properties check:', hasRole ? 'Found role property' : 'No role property found');
              return hasRole;
            } catch (error) {
              console.log('Error checking properties:', error.message);
              core.setOutput('has_properties', false);
              return false;
            }
      
      - name: Create setup issue for Copilot agent
        if: steps.check_properties.outputs.has_properties == 'false'
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const issueBody = `## Repository Setup Required
            
            This repository was created from the SDD template and needs custom properties configured.
            
            ### Task: Set Repository Properties
            
            Please set the following custom repository properties using the GitHub API:
            
            1. **role**: Set to \`spec\` if this is a specification repository, or \`feature\` if this implements another specification
            2. **spec**: Only set this if role=feature - should contain the full repository slug of the spec this implements (e.g., "Avanavo/my-spec-repo")
            
            ### API Details
            Use the GitHub REST API endpoint:
            \`PATCH /repos/${context.repo.owner}/${context.repo.repo}/properties/values\`
            
            With JSON body:
            \`\`\`json
            {
              "properties": {
                "role": "spec",
                "spec": ""
              }
            }
            \`\`\`
            
            ### Expected Result
            After setting properties:
            - Comment on this issue confirming what values were set
            - Close this issue
            
            ### Default Recommendation
            Since this is a new repository, likely set \`role=spec\` unless the repository name or content clearly indicates it's a feature implementation.
            
            Repository: \`${context.repo.owner}/${context.repo.repo}\`
            `;
            
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Setup Repository Properties',
              body: issueBody,
              assignees: ['github-copilot[bot]'],
              labels: ['setup', 'automation', 'copilot-task']
            });
            
            console.log(`Created setup issue #${issue.data.number} assigned to Copilot agent`);
            return issue.data.html_url;
