name: Setup Repository Properties

on:
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force run even if properties exist'
        required: false
        default: false
        type: boolean

jobs:
  setup-properties:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Authentication
        id: setup_auth
        run: |
          # Using user access token directly (TODO: move to secrets)
          echo "Using user access token"
          echo "token=ghu_trClkpgQpZpal9yoFGwIjtDTnHO2uG1EjPTa" >> $GITHUB_OUTPUT
          echo "auth_type=user_token" >> $GITHUB_OUTPUT
      
      - name: Debug Authentication and Permissions
        run: |
          echo "Repository owner: ${{ github.repository_owner }}"
          echo "Authentication type: ${{ steps.setup_auth.outputs.auth_type }}"
          echo "Token length: ${#GH_TOKEN}"
          
          # Check what permissions this token has
          echo "Checking token permissions..."
          gh api /user --jq '{login: .login, type: .type}' || echo "Failed to get user info"
          
          # Check repository access
          echo "Checking repository access..."
          gh api "/repos/${{ github.repository }}" --jq '{name: .name, permissions: .permissions}' || echo "Failed to get repository info"
        env:
          GH_TOKEN: ${{ steps.setup_auth.outputs.token }}
      
      - name: Check if properties already exist
        id: check_properties
        run: |
          echo "Checking if repository properties already exist..."
          
          # Use gh api to check for existing properties
          if gh api "/repos/${{ github.repository }}/properties/values" --jq '.[].property_name' | grep -q "role"; then
            echo "has_properties=true" >> $GITHUB_OUTPUT
            echo "✅ Found existing 'role' property - skipping setup"
          else
            echo "has_properties=false" >> $GITHUB_OUTPUT
            echo "❌ No 'role' property found - setup needed"
          fi
        env:
          GH_TOKEN: ${{ steps.setup_auth.outputs.token }}
      

      - name: Set repository properties automatically
        if: steps.check_properties.outputs.has_properties == 'false' || github.event.inputs.force_run == 'true'
        run: |
          echo "Setting repository properties automatically..."
          
          # Determine the role - default to 'spec' for new repositories
          REPO_ROLE="spec"
          REPO_SPEC="null"
          
          echo "Setting properties:"
          echo "  role: $REPO_ROLE"
          echo "  spec: $REPO_SPEC"
          
          # Create JSON payload for properties
          JSON_PAYLOAD='{"properties":[{"property_name":"role","value":"'$REPO_ROLE'"},{"property_name":"spec","value":'$REPO_SPEC'}]}'
          echo "Setting properties with payload: $JSON_PAYLOAD"
          
          # Set the properties using GitHub API
          if echo "$JSON_PAYLOAD" | gh api --method PATCH "/repos/${{ github.repository }}/properties/values" --input -; then
            echo "✅ Successfully set repository properties"
            echo "Repository is configured as a specification repository (role=spec, spec=null)"
          else
            echo "❌ Failed to set repository properties"
            echo "This might be due to insufficient permissions or missing custom property definitions"
            echo "Please check that custom properties 'role' and 'spec' are defined in your organization settings"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ steps.setup_auth.outputs.token }}
